/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BigNumberish
} from "ethers";


export declare namespace Pairing {
  export type G1PointStruct = { x: BigNumberish; y: BigNumberish };

  export type G1PointStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };

  export type G2PointStruct = {
    x: [BigNumberish, BigNumberish];
    y: [BigNumberish, BigNumberish];
  };

  export type G2PointStructOutput = [
    x: [bigint, bigint],
    y: [bigint, bigint]
  ] & { x: [bigint, bigint]; y: [bigint, bigint] };
}

export declare namespace SnarkCommon {
  export type VerifyingKeyStruct = {
    alpha1: Pairing.G1PointStruct;
    beta2: Pairing.G2PointStruct;
    gamma2: Pairing.G2PointStruct;
    delta2: Pairing.G2PointStruct;
    ic: Pairing.G1PointStruct[];
  };

  export type VerifyingKeyStructOutput = [
    alpha1: Pairing.G1PointStructOutput,
    beta2: Pairing.G2PointStructOutput,
    gamma2: Pairing.G2PointStructOutput,
    delta2: Pairing.G2PointStructOutput,
    ic: Pairing.G1PointStructOutput[]
  ] & {
    alpha1: Pairing.G1PointStructOutput;
    beta2: Pairing.G2PointStructOutput;
    gamma2: Pairing.G2PointStructOutput;
    delta2: Pairing.G2PointStructOutput;
    ic: Pairing.G1PointStructOutput[];
  };
}
